os: linux
dist: xenial
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - cd docs &&
    make html
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "wilsja.me"
    edge: true # opt in to dpl v2
    local_dir: ./build/html
    on:
        branch: main
