language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - cd docs &&
    make html
deploy:
    skip_cleanup: true # keep build 
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_KEY
    acl: public_read
    bucket: "wilsja.me"
    edge: true # opt in to dpl v2
    local_dir: /build/html
    on:
        all_branches: main
